version: '3.9'

services:

  web:
    build: .
    ports:
      - "8080:80"

  mysql:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mpm
      MYSQL_USER: amaury
      MYSQL_PASSWORD: 12345678

    ports:
      - "3306:3306"